### ISSUE TITLE
準備用ビークルを呼び出す機能の追加

### ISSUE THREAD

**Issue by shairo** [shairo/SW_BattleMatchmaker#2]
- コマンドで準備用ビークルをSpawn/Despawnさせる
- 準備用ビークルには衣服、チーム参加ボタン、トーチ供給ボタン等を用意する
- コマンドを実行する度に前のビークルは削除する
- vehicle_idはg_savedataに保存し不慮のクラッシュ等に備える

**Comment by unippu** [comment]
実行のたびに前のビークルを削除してしまうと、２チーム同時に別々の場所で準備しようというときに片方しか作業できない恐れがあるので、環境MODとして設置してタイマーのentry変数が真の間だけ出すようにするという処理はどうでしょうか？
もし想定しているものに齟齬があるようでしたらもう少し詳しい仕様を教えてください。

**Comment by shairo** [comment]
環境MODとして出すと場所を選べなくなるのが難なんですよね。
全ワークベンチに置くってのも無駄ですし・・・

同時に二つ出せないようにというのは単に自分の好み＆コードがシンプルで済むからで深い理由はありません。
でもAdminがわざわざ両チーム側に飛んでスポーンさせるのも手間でやらせたくない気持ちがあります。
開始時に自動削除は賛成です

**Comment by unippu** [comment]
ではそれぞれのチームで連携して順番に出してもらうっていう運用で様子見て、混乱が生じるようであれば複数同時も検討して行くという方針でどうでしょう。

**Comment by shairo** [comment]
スポーンコマンドはAdmin用という認識だったけど、よく考えてみたら別に非Adminが出せても問題ないですね。それでいきましょう

**Comment by unippu** [comment]
了解です！

**Comment by shairo** [comment]
Done

**Comment by shairo** [comment]
Done
