### ISSUE TITLE
プレイヤー体力の回復など

### ISSUE THREAD

**Issue by shairo** [shairo/SW_BattleMatchmaker#5]
円滑にゲームを進めるためゲーム開始・終了時にプレイヤー体力を回復する

**Comment by unippu** [comment]
合わせて双眼鏡とコンパスも付与するのはどうでしょうか？
スロット系の値若干増えちゃいますが、たまに人が死ぬ（＝アイテム全ロス）っていうことが発生していることを考えると、そういった小物も一括で付与できたら便利かと思いました。
やることとしては、その関数を作るのと、アイテム系の配列にスロット番号を増やすことでしょうか？

**Comment by shairo** [comment]
いいですね。特に双眼鏡は無いと困りますしね・・

**Comment by shairo** [comment]
#7 で対応
